version: "3.8"

services:

  bf-mongodb:
    image: mongo
    container_name: bf-mongodb
    hostname: mongodb
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - mongo_personal_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=bufunfa
    networks:
      default:
        aliases:
          - mongodb

  bf-api:
    container_name: bufunfa-api
    build:
      dockerfile: ./deploy/bf/api.dockerfile
      context: ../../
    restart: always
    env_file:
      - .env.api
    networks:
      - default
    ports:
      - "8002:8002"

  bf-front:
    volumes:
      - bf_front_dist_vol:/usr/share/nginx/html
    container_name: bufunfa-front
    build:
      dockerfile: deploy/bf/nginx.dockerfile
      context: ../../
    restart: always
    env_file:
      - .env.front
    networks:
      - default
    ports:
      - "8082:8082"

networks:
  default: {}

volumes:
  mongo_personal_volume:
    external: true
  bf_front_dist_vol:
    external: true
